-- ============================================================
-- TABEL: agendas (Fitur Agenda Kegiatan Sekolah)
-- Jalankan di Supabase Dashboard > SQL Editor
-- ============================================================

create table if not exists public.agendas (
  id bigint generated by default as identity primary key,
  judul text not null,
  tanggal date not null,
  jam text default '',
  lokasi text default '',
  keterangan text default '',
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agendas enable row level security;

create policy "agendas_select" on public.agendas for select using (true);
create policy "agendas_insert" on public.agendas for insert with check (true);
create policy "agendas_update" on public.agendas for update using (true) with check (true);
create policy "agendas_delete" on public.agendas for delete using (true);

alter table public.agendas replica identity full;

-- Contoh data awal (opsional)
insert into public.agendas (judul, tanggal, jam, lokasi, keterangan, status) values
  ('Rapat Kerja Dewan Guru', current_date + interval '3 day', '08.00 - 12.00', 'Aula Sekolah', 'Rapat koordinasi awal tahun ajaran.', 'published'),
  ('Peringatan HUT Sekolah', current_date + interval '10 day', '07.30 - 13.00', 'Lapangan Sekolah', 'Upacara dan pentas seni siswa.', 'published')
on conflict do nothing;
